system: 
  ip: 
  port: 8080
  env: dev
log:
  dir: logs
  app: project-template
db:
  user: root
  password: lianGjh3303..
  host: localhost
  port: 3306
  using: naotodo
  debug: false
gin:
  ip: 
  port: 3303
  env: dev
