server:
    ip:
    port: 3302
    version: 1.0
    jwtSecret: NaoTodoServerJwtSecret

mysql:
    host: localhost
    port: 3306
    database: naotodo_test
    username: root
    password: lianGjh3303..
    charset: utf8mb4
    parseTime: True
    loc: Local

redis:
    host: localhost
    port: 6379
    password: lianGjh3303!
    database: 0
    network: tcp
